insert into JUEZ (DNI, NOMBRES, APELLIDOS, NRO_COLEGIATURA, USUARIO, CONTRASENA, JUZGADO_ID, SEXO_ID) values (38752778, 'Yetty', 'Teck', 0016, 'YTeck', 'YTeck', 2, 1);
insert into JUEZ (DNI, NOMBRES, APELLIDOS, NRO_COLEGIATURA, USUARIO, CONTRASENA, JUZGADO_ID, SEXO_ID) values (34853727, 'Jarad', 'Codrington', 0017, 'JCodrington', 'JCodrington', 1, 1);
insert into JUEZ (DNI, NOMBRES, APELLIDOS, NRO_COLEGIATURA, USUARIO, CONTRASENA, JUZGADO_ID, SEXO_ID) values (44833942, 'Lilian', 'Chattey', 0018, 'LChattey', 'LChattey', 1, 1);
insert into JUEZ (DNI, NOMBRES, APELLIDOS, NRO_COLEGIATURA, USUARIO, CONTRASENA, JUZGADO_ID, SEXO_ID) values (63476939, 'Lucky', 'Bampford', 0019, 'LBampford', 'LBampford', 2, 2);
insert into JUEZ (DNI, NOMBRES, APELLIDOS, NRO_COLEGIATURA, USUARIO, CONTRASENA, JUZGADO_ID, SEXO_ID) values (39329348, 'Napoleon', 'Meldon', 0020, 'NMeldon', 'NMeldon', 2, 1);
