CREATE OR REPLACE FUNCTION GETPSWD (USUARIO_INPUT IN VARCHAR2) RETURN
VARCHAR2 IS
 CURSOR JUECES IS
 SELECT CONTRASENA FROM JUEZ WHERE USUARIO = USUARIO_INPUT;
 TIENE_RECORDS BOOLEAN := FALSE;
BEGIN
 FOR ITEM IN JUECES LOOP
 TIENE_RECORDS := TRUE;
 RETURN ITEM.CONTRASENA;
 END LOOP;
 IF NOT TIENE_RECORDS THEN
 RETURN 'null';
 END IF;
END;