from configs.database import engine

def get_all_by_id(juez_id):
  conn = engine.connect()
  stmt = (f"""
    SELECT DEMANDA.ID AS DEMANDA_ID, DEMANDA.NRO_SOLICITUD, DEMANDADO.NOMBRES AS DEMANDADO_NOMBRES, DEMANDANTE.NOMBRES AS DEMANDANTE_NOMBRES, ESTADODEMANDA.NOMBRE AS ESTADODEMANDA_NOMBRE, TIPODEMANDA.NOMBRE AS TIPODEMANDA_NOMBRE FROM DEMANDA
    INNER JOIN DEMANDANTE ON demanda.demandante_id = DEMANDANTE.id
    INNER JOIN DEMANDADO ON demanda.demandado_id = DEMANDADO.id
    INNER JOIN ESTADODEMANDA ON estadodemanda_id = estadodemanda.id
    INNER JOIN TIPODEMANDA ON demanda.tipodemanda_id = tipodemanda.id
    WHERE JUEZ_ID = {juez_id}""")
  return [dict(r) for r in conn.execute(stmt)]

def get_demanda_detail_by_id(demanda_id):
  conn = engine.connect()
  stmt = (f"""
    SELECT

    D.DESCRIPCION AS DEMANDA_DESCRIPCION,
    D.NRO_SOLICITUD AS DEMANDA_NRO_SOLICITUD,
    D.FECHA_EMISION AS DEMANDA_FECHA_EMISION,
    D.DEMANDANTE_ID AS DEMANDA_DEMANDANTE_ID,
    D.DEMANDADO_ID AS DEMANDA_DEMANDADO_ID,
    D.DEMANDANTE_ABOGADO_ID AS DEMANDA_DEMANDANTE_ABOGADO_ID,
    D.DEMANDADO_ABOGADO_ID AS DEMANDA_DEMANDADO_ABOGADO_ID,

    DE.ID AS DEMANDANTE_ID,
    DE.NOMBRES AS DEMANDANTE_NOMBRES,
    DE.APELLIDOS AS DEMANDANTE_APELLIDOS,
    DE.DNI AS DEMANDANTE_DNI,
    DE.DIRECCION AS DEMANDANTE_DIRECCION,
    DE.SEXO_ID AS DEMANDANTE_SEXO_ID,

    DO.ID AS DEMANDADO_ID,
    DO.NOMBRES AS DEMANDADO_NOMBRES,
    DO.APELLIDOS AS DEMANDADO_APELLIDOS,
    DO.DNI AS DEMANDADO_DNI,
    DO.DIRECCION AS DEMANDADO_DIRECCION,
    DO.SEXO_ID AS DEMANDADO_SEXO_ID,

    DEA.ID AS ABOGADO_DEMANDANTE_ID,
    DEA.NOMBRES AS ABOGADO_DEMANDANTE_NOMBRES,
    DEA.APELLIDOS AS ABOGADO_DEMANDANTE_APELLIDOS,
    DEA.DNI AS ABOGADO_DEMANDANTE_DNI,
    DEA.SEXO_ID AS ABOGADO_DEMANDANTE_SEXO_ID,
    DEA.NRO_COLEGIATURA AS ABOGADO_DEMANDANTE_NRO_C,

    DOA.ID AS ABOGADO_DEMANDADO_ID,
    DOA.NOMBRES AS ABOGADO_DEMANDADO_NOMBRES,
    DOA.APELLIDOS AS ABOGADO_DEMANDADO_APELLIDOS,
    DOA.DNI AS ABOGADO_DEMANDADO_DNI,
    DOA.SEXO_ID AS ABOGADO_DEMANDADO_SEXO_ID,
    DOA.NRO_COLEGIATURA AS ABOGADO_DEMANDADO_NRO_C,

    SDE.ID AS SEXO_ID_DE,
    SDE.NOMBRE AS DE_SEXO_NOMBRE,

    SDO.ID AS SEXO_ID_DO,
    SDO.NOMBRE AS DO_SEXO_NOMBRE,

    SDEA.ID AS SEXO_ID_DEA,
    SDEA.NOMBRE AS DEA_SEXO_NOMBRE,

    SDOA.ID AS SEXO_ID_DOA,
    SDOA.NOMBRE AS DOA_SEXO_NOMBRE

    FROM DEMANDA D
    INNER JOIN DEMANDANTE DE ON D.DEMANDANTE_ID = DE.ID
    INNER JOIN DEMANDADO DO ON D.DEMANDADO_ID = DO.ID
    INNER JOIN ABOGADO DEA ON D.DEMANDANTE_ABOGADO_ID = DEA.ID
    INNER JOIN ABOGADO DOA ON D.DEMANDADO_ABOGADO_ID = DOA.ID

    INNER JOIN SEXO SDE ON DE.SEXO_ID = SDE.ID
    INNER JOIN SEXO SDO ON DO.SEXO_ID = SDO.ID
    INNER JOIN SEXO SDEA ON DEA.SEXO_ID = SDEA.ID
    INNER JOIN SEXO SDOA ON DOA.SEXO_ID = SDOA.ID

    WHERE D.ID = {demanda_id}""")
  return [dict(r) for r in conn.execute(stmt)]
