from configs.database import engine

def get_by_dni(expediente_dni):
    conn = engine.connect()
    stmt = (f"""
        SELECT 

        E.NRO_EXPEDIENTE AS EXPEDIENTE_NRO,
        E.OBSERVACIONES AS EXPEDIENTE_OBSERVACIONES,
        E.FORMRENIEC_ID AS EXPEDIENTE_RENIEC_ID,
        E.FORMSUNARP_ID AS EXPEDIENTE_SUNARP_ID,
        E.FORMMINTRABAJO_ID AS EXPEDIENTE_MINTRABAJO_ID,
        E.SECRETARIOJUDICIAL_ID AS EXPEDIENTE_SECRETARIO_ID,

        FR.ID AS RENIEC_ID,
        FR.NOMBRES AS RENIEC_NOMBRES,
        FR.APELLIDOS AS RENIEC_APELLIDOS,
        FR.DNI AS RENIEC_DNI,
        FR.DIRECCION AS RENIEC_DIRECCION,
        FR.SEXO_ID AS RENIEC_SEXO_ID,
        FR.ESTADOCIVIL_ID AS RENIEC_ESTADOCIVIL_ID,
        FR.GRADOINSTRUCCION_ID AS RENIEC_INSTRUCCION_ID,

        FS.ID AS SUNARP_ID,
        FS.NRO_PROPIEDADES AS SUNARP_NRO_PROPIEDADES,
        FS.NRO_VEHICULOS AS SUNARP_NRO_VEHICULOS,
        FS.OBSERVACIONES AS SUNARP_OBSERVACIONES,

        FMT.ID AS MINTRABAJO_ID,
        FMT.NOMBRE_LUGAR_TRABAJO AS MINTRABAJO_LUGAR,
        FMT.RUC_LUGAR_TRABAJO AS MINTRABAJO_RUC,
        FMT.MONTO_INGRESO AS MINTRABAJO_MONTO,
        FMT.OBSERVACIONES AS MINTRABAJO_OBSERVACIONES,

        SJ.ID AS SECRETARIO_ID,
        SJ.DNI AS SECRETARIO_DNI,
        SJ.NOMBRES AS SECRETARIO_NOMBRES,
        SJ.APELLIDOS AS SECRETARIO_APELLIDOS,
        SJ.NRO_COLEGIATURA AS SECRETARIO_NRO_COLEGIATURA,
        SJ.SEXO_ID AS SECRETARIO_SEXO_ID,

        SR.ID AS SEXO_ID_R,
        SR.NOMBRE AS R_SEXO_NOMBRE,

        SS.ID AS SEXO_ID_SS,
        SS.NOMBRE AS S_SEXO_NOMBRE_SS,

        EC.ID AS ESTADO_CIVIL_ID,
        EC.NOMBRE AS R_ESTADOCIVIL_NOMBRE,

        GI.ID AS GRADO_INSTITUCION_ID,
        GI.NOMBRE AS R_GRADO_INSTITUCION_NOMBRE

        FROM EXPEDIENTE E
        INNER JOIN FORMRENIEC FR ON E.FORMRENIEC_ID = FR.ID
        INNER JOIN FORMSUNARP FS ON E.FORMSUNARP_ID = FS.ID
        INNER JOIN FORMMINTRABAJO FMT ON E.FORMMINTRABAJO_ID = FMT.ID
        INNER JOIN FORMSUNARP FS ON E.FORMSUNARP_ID = FS.ID
        INNER JOIN SECRETARIOJUDICIAL SJ ON E.SECRETARIOJUDICIAL_ID = SJ.ID
        INNER JOIN SEXO SR ON FR.SEXO_ID = SR.ID 
        INNER JOIN SEXO SS ON SJ.SEXO_ID = SS.ID
        INNER JOIN ESTADOCIVIL EC ON FR.ESTADOCIVIL_ID = EC.ID
        INNER JOIN GRADOINSTRUCCION GI ON FR.GRADOINSTRUCCION_ID = GI.ID

        WHERE FR.DNI = {expediente_dni}""")
    return [dict(r) for r in conn.execute(stmt)]