from configs.database import engine

def get_all(juez_id):
  conn = engine.connect()
  stmt = (f"""
  SELECT JUEZ.NOMBRES AS JUEZ_NOMBRES, JUEZ.APELLIDOS AS JUEZ_APELLIDOS, JUEZ.NRO_COLEGIATURA, JUEZ.DNI AS JUEZ_DNI, JUEZ.USUARIO AS JUEZ_USUARIO, JUEZ.CONTRASENA AS JUEZ_CONTRASENA, JUZGADOPAZLETRADO.DIRECCION AS JUEZ_DIRECCION, SEXO.NOMBRE AS JUEZ_SEXO FROM JUEZ
  INNER JOIN JUZGADOPAZLETRADO ON JUEZ.JUZGADO_ID = JUZGADOPAZLETRADO.ID
  INNER JOIN SEXO ON JUEZ.SEXO_ID = SEXO.ID
  WHERE JUEZ_ID = {juez_id}""")
  return [dict(r) for r in conn.execute(stmt)]
