insert into JUEZ (DNI, NOMBRES, APELLIDOS, NRO_COLEGIATURA, USUARIO, CONTRASENA, JUZGADO_ID, SEXO_ID) values (24916108, 'Yetty', 'Teck', 46403, 'YTeck', 'YTeck', 2, 1);
insert into JUEZ (DNI, NOMBRES, APELLIDOS, NRO_COLEGIATURA, USUARIO, CONTRASENA, JUZGADO_ID, SEXO_ID) values (42878755, 'Jarad', 'Codrington', 74576, 'JCodrington', 'JCodrington', 1, 1);
insert into JUEZ (DNI, NOMBRES, APELLIDOS, NRO_COLEGIATURA, USUARIO, CONTRASENA, JUZGADO_ID, SEXO_ID) values (88136017, 'Lilian', 'Chattey', 89859, 'LChattey', 'LChattey', 1, 1);
insert into JUEZ (DNI, NOMBRES, APELLIDOS, NRO_COLEGIATURA, USUARIO, CONTRASENA, JUZGADO_ID, SEXO_ID) values (94372203, 'Lucky', 'Bampford', 17256, 'LBampford', 'LBampford', 2, 2);
insert into JUEZ (DNI, NOMBRES, APELLIDOS, NRO_COLEGIATURA, USUARIO, CONTRASENA, JUZGADO_ID, SEXO_ID) values (63094695, 'Napoleon', 'Meldon', 68671, 'NMeldon', 'NMeldon', 2, 1);
