insert into FORMRENIEC (DNI, NOMBRES, APELLIDOS, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) values (29909077, 'Wilow', 'Filipowicz', '421 Lotheville Point', 1, 3, 1);
insert into FORMRENIEC (DNI, NOMBRES, APELLIDOS, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) values (79728897, 'Bonnie', 'Garfit', '90648 Blue Bill Park Center', 1, 0, 1);
insert into FORMRENIEC (DNI, NOMBRES, APELLIDOS, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) values (15891548, 'Schuyler', 'Bosworth', '79 Buhler Court', 1, 2, 1);
insert into FORMRENIEC (DNI, NOMBRES, APELLIDOS, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) values (32553794, 'Horst', 'Grima', '366 Laurel Way', 2, 3, 0);
insert into FORMRENIEC (DNI, NOMBRES, APELLIDOS, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) values (12908086, 'Tomas', 'Dummigan', '44 Barby Place', 0, 1, 0);

insert into FORMRENIEC (DNI, NOMBRES, APELLIDOS, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) values (97329197, 'Dion', 'Bengough', '52 Dahle Park', 2, 0, 1);
insert into FORMRENIEC (DNI, NOMBRES, APELLIDOS, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) values (62242600, 'Lewes', 'Piggins', '271 Warner Park', 1, 3, 0);
insert into FORMRENIEC (DNI, NOMBRES, APELLIDOS, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) values (98785140, 'Griffy', 'Liddy', '99 Sherman Alley', 0, 1, 1);
insert into FORMRENIEC (DNI, NOMBRES, APELLIDOS, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) values (19365900, 'Christalle', 'Sterre', '619 Lunder Park', 1, 2, 1);
insert into FORMRENIEC (DNI, NOMBRES, APELLIDOS, DIRECCION, ESTADOCIVIL_ID, GRADOINSTRUCCION_ID, SEXO_ID) values (31989683, 'Miguelita', 'Jaycocks', '413 Superior Place', 3, 0, 0);
